# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srFrontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtextfield',
            old_name='question_text',
            new_name='text',
        ),
    ]
