# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srFrontend', '0003_auto_20160130_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webtextfield',
            old_name='pub_date',
            new_name='pub_Date',
        ),
    ]
