# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srFrontend', '0004_auto_20160202_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_Name', models.CharField(max_length=200)),
                ('image_Path', models.CharField(max_length=256)),
                ('image_Type', models.IntegerField(choices=[(0, 'Background'), (1, 'Carousel'), (2, 'Standard')])),
            ],
        ),
    ]
